config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :entries

  get '/' => 'home#index', as: 'home'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get '/articles' => 'articles#index'
  # get 'articles/new' => 'articles#new', as: 'new_article'
  # post '/articles' => 'articles#create', as: 'create_article' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :author, presence: true, uniqueness: true
    validates :body, presence: true, length: { minimum: 5 }
end

app/models/entry.rb
class Entry < ApplicationRecord
    validates :title, :author, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new
        @article.name = params[:name]
        @article.body = params[:body]

        respond_to do |format|
            if @article.save
                format.html { redirect_to entry_url(@article), notice: "Article was successfully created." }
                format.json { render :show, status: :created, location: @article }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @article.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
    end
    
    def update
        respond_to do |format|
          if @article.update(article_params)
            format.html { redirect_to entry_url(@article), notice: "Article was successfully updated." }
            format.json { render :show, status: :ok, location: @article }
          else
            format.html { render :edit, status: :unprocessable_entity }
            format.json { render json: @article.errors, status: :unprocessable_entity }
          end
        end
    end
    
    
    def destroy
        @article.destroy
    
        respond_to do |format|
          format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    private

    def article_params
        params.require(:article).permit(:name, :body)
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:title, :author, :body, :published)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]


  def index
    @entries = Entry.all
  end


  def show
  end


  def new
    @entry = Entry.new
  end


  def edit
  end


  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
   
    def set_entry
      @entry = Entry.find(params[:id])
    end

   
    def entry_params
      params.require(:entry).permit(:title, :author, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/index.html.erb
<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Author</th>
            <th>Body</th>
        </tr>

    <thead>

    <tbody>
    <%  @articles.each do |article| %>
        <tr>
            <td><%= article.id %> </td>
            <td><%= article.name %> </td>
            <td><%= article.author %> </td>
            <td><%= article.body %> </td>
        </tr>
    <% end %>
    </tbody>
</table>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<%= form_with url: create_article_path, local: true do |f| %>

<p>
    <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    
    <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :author %><br/>
    <%= f.text_field :author %>
</p>

<p>
    <%= f.label :body %><br/>
    <%= f.text_field :body %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/entries/_entry.html.erb
<div class='container'>
<div id="<%= dom_id entry %>">
<p>
    <strong>Title:</strong>
    <%= entry.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= entry.author %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= entry.body %>
  </p>
</div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/_nav.html.erb
<nav>
    <%= link_to "home", home_path %>
    <span>about</span>        
    <span>socials</span>
    <span>faq</span>
    <span>contact</span>
</nav>

app/views/entries/edit.html.erb
<section>
<%= render "nav" %>
<div class='container'>
<h2>Edit entry</h2>
<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", home_path %>
</div>
</div>
</section>

app/views/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entries</h1>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
    <p>
      <%= link_to "Show this entry", entry %>
    </p>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path %>

app/views/entries/new.html.erb
<section class='new-section'>
<%= render "nav" %>
<div class='new-container'>
<h2>New entry</h2>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", home_path %>
</div>
</div>
</section>

app/views/entries/show.html.erb
<%= render "nav" %>
<p style="color: green"><%= notice %></p>
<section>
<div class='container'>
<%= render @entry %>

<div class='edit-entry'>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", home_path %> |
  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>
</div>
</section>

app/views/home/_entry.html.erb
<div id="entry">
  <p>
    <strong>Title:</strong>
    <%= entry.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= entry.author %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= entry.body %>
  </p>

</div>

app/views/home/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/home/_nav.html.erb
<nav>
    <span>hello</span>
    <span>about</span>        
    <span>socials</span>
    <span>faq</span>
    <span>contact</span>
</nav>

app/views/home/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/home/index.html.erb
<section>

    <%= render "nav" %>

    <div id='container'>
        <span id='date'> </span>
        <hr>
        <h1>Welcome to my blog!</h1>
        
        <div class="entries">
        <% @entries.each do |entry| %>
        <div class='entry'>
          <%= render "entry",entry:entry %>
          <p>
            <%= link_to "Show this entry", entry %>
          </p>
        </div>
        <% end %>
      </div>
      
      
      <%= link_to "New entry", new_entry_path %>
      

    </div>

</section>

app/views/home/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/home/show.html.erb
<p style="color: green"><%= notice %></p>
<% debugger %>
<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= yield %> 
  </body>
</html>